package com.oneguy.live.control.wsdl;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 24/06/2016
//
//---------------------------------------------------



public class OperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public Object Tag;
    public String MethodName;
}
